/* Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example: 
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added. */

//Solution 1
class Solution {
public:
    char findTheDifference(string s, string t) 
    {
        int list[26]={0};
        for(auto ch:t)
            ++list[ch-'a'];
        for(auto ch:s)
            --list[ch-'a'];
        for(int i=0;i!=26;++i)
            if(list[i])
                return i+'a';
    }
        
};

//Solution 2
class Solution {
public:
    char findTheDifference(string s, string t) 
    {
        unsigned char result=0;
        for(auto ch:t)
            result+=ch;
        for(auto ch:s)
            result-=ch;
        return result;
    }
        
};